export const tokens = {
  colors: {
    bg: 'var(--kaze-bg)',
    surface: 'var(--kaze-surface)',
    surfaceHover: 'var(--kaze-surface-hover)',
    surfaceActive: 'var(--kaze-surface-active)',
    border: 'var(--kaze-border)',
    borderStrong: 'var(--kaze-border-strong)',
    text: 'var(--kaze-text)',
    textSecondary: 'var(--kaze-text-secondary)',
    textTertiary: 'var(--kaze-text-tertiary)',
    accent: 'var(--kaze-accent)',
    accentHover: 'var(--kaze-accent-hover)',
    accentText: 'var(--kaze-accent-text)',
    destructive: 'var(--kaze-destructive)',
    destructiveLight: 'var(--kaze-destructive-light)',
    success: 'var(--kaze-success)',
    successLight: 'var(--kaze-success-light)',
    info: 'var(--kaze-info)',
    infoLight: 'var(--kaze-info-light)',
    warning: 'var(--kaze-warning)',
    warningLight: 'var(--kaze-warning-light)',
    ring: 'var(--kaze-ring)',
    overlay: 'var(--kaze-overlay)',
  },
}
