/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeRouteImport } from './routes/theme'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsSlugRouteImport } from './routes/components/$slug'

const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSlugRoute = ComponentsSlugRouteImport.update({
  id: '/components/$slug',
  path: '/components/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/theme': typeof ThemeRoute
  '/components/$slug': typeof ComponentsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/theme': typeof ThemeRoute
  '/components/$slug': typeof ComponentsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/theme': typeof ThemeRoute
  '/components/$slug': typeof ComponentsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/theme' | '/components/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/theme' | '/components/$slug'
  id: '__root__' | '/' | '/theme' | '/components/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThemeRoute: typeof ThemeRoute
  ComponentsSlugRoute: typeof ComponentsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$slug': {
      id: '/components/$slug'
      path: '/components/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThemeRoute: ThemeRoute,
  ComponentsSlugRoute: ComponentsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
